### ISSUE TITLE
Make reqwest/OpenSSL an optional dependency

### ISSUE THREAD

**Issue by tscs37** [wisespace-io/yubico-rs#5]
For a current project, the reqwest dependency introduces an unwanted openssl linkage, I build to a muslc target which makes linking OpenSSL rather cumbersome and the final project will not make use of the verification feature that Yubico offers. Since I can't link OpenSSL I made a small patch which introduces a new "online" feature. By setting default features to false, the crate will build without any online functionality (ie, verifying codes against the yubico servers), this functionality is enabled by using the `online` feature.

The patch mostly consists of disabling various code via a `#[cfg]` macro.

[yubico-rs.patch](https://github.com/wisespace-io/yubico-rs/files/2592026/yubico-rs.patch.txt)

**Comment by wisespace-io** [comment]
@tscs37 I tried your patch but it always failed to build with the error below:

  |                                                                                                                                                                      
5 | extern crate reqwest;                                                                                                                                                
  | ^^^^^^^^^^^^^^^^^^^^^ can't find crate 

So, I added:

    online = ["reqwest"]

Now, in order to build the library **without** reqwest: 

     yubico = { version = "0.4", default-features = false }

And, in order to **include** reqwest:

     yubico = { version = "0.4" }

I will include your patch after test a little more later, ok?

**Comment by wisespace-io** [comment]
@tscs37 https://github.com/wisespace-io/yubico-rs/commit/07cb2dc2dc1352bdccf802ed963b02d7e2226ce9

**Comment by tscs37** [comment]
Thanks, I probably missed a line in the patchfile. looks okay to me otherwise :smiley:
